services:
  postgres_bria:
    image: postgres:16
    container_name: postgres_bria
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  metricas_bria:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metricas_bria
    depends_on:
      - postgres_bria
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./data:/data
    command: python main.py
    restart: "no"

volumes:
  postgres_data:
